apps/auctions/urls.py
from django.urls import path

from .views import (
    AuctionCreateView,
    AuctionDetailView,
    AuctionListView,
    CreateBidView,
    PaymentSuccessView,
    PaymentView,
    payment_webhook,
)

app_name = "auctions"

urlpatterns = [
    path("", AuctionListView.as_view(), name="list"),
    path("<int:pk>", AuctionDetailView.as_view(), name="detail"),
    path("<int:pk>/bid", CreateBidView.as_view(), name="bid"),
    path("create", AuctionCreateView.as_view(), name="create"),
    path("<int:pk>/pay", PaymentView.as_view(), name="pay"),
    path("payment/success", PaymentSuccessView.as_view(), name="payment-successful"),
    path("payment/hook", payment_webhook, name="payment-hook"),
]

config/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from apps.auctions import views as auctions_views

urlpatterns = [
    path("", auctions_views.HomeView.as_view(), name="home"),
    path("accounts/", include("apps.accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("auctions/", include("apps.auctions.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    if apps.is_installed("debug_toolbar"):
        urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/auctions/models.py
from decimal import Decimal

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


def media_directory_path(instance, filename):
    return f"{instance.auction.owner_id}/{instance.auction.id}/{filename}"


class Auction(models.Model):
    class Status(models.TextChoices):
        NEW = "NEW", _("New")
        CANCELLED = "CANCELLED", _("Cancelled")
        PAYMENT_PENDING = "PAYMENT_PENDING", _("Payment Pending")
        COMPLETE = "COMPLETE", _("Complete")

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(max_length=15, choices=Status.choices, default=Status.NEW)
    short_description = models.CharField(max_length=128)
    description = models.TextField()
    initial_price = models.DecimalField(
        max_digits=8, decimal_places=2, validators=[MinValueValidator(Decimal(1.0))]
    )
    end_date = models.DateTimeField()

    def __str__(self):
        return f"{self.short_description}"

    @property
    def current_price(self):
        bid = self.current_bid
        return bid.amount if bid else self.initial_price

    @property
    def current_bid(self):
        return self.bids.last()

    @property
    def expired(self):
        return timezone.now() >= self.end_date

    def get_absolute_url(self):
        return reverse("auctions:detail", args=[self.id])


class AuctionImage(models.Model):
    auction = models.ForeignKey(
        "Auction", on_delete=models.CASCADE, related_name="images"
    )
    src = models.ImageField(upload_to=media_directory_path)
    description = models.TextField()

    def __str__(self):
        return f"{self.auction.short_description} - {self.description}"


class Bid(models.Model):
    auction = models.ForeignKey(
        "Auction", on_delete=models.CASCADE, related_name="bids"
    )
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    bidder = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-date"]

    def clean(self):
        if self.auction.current_price >= self.amount:
            raise ValidationError(_("Bid amount should be greater than current amount"))
        if self.auction.current_bid and self.auction.current_bid.bidder == self.bidder:
            raise ValidationError(_("Already bid on this auction"))
        if self.auction.expired:
            raise ValidationError(_("Auction has expired"))
        if self.auction.owner == self.bidder:
            raise ValidationError(_("You own the auction"))

    def __str__(self):
        return f"{self.auction.short_description} (${self.amount})"

apps/auctions/forms.py
from django.forms import ModelForm, inlineformset_factory

from .models import Auction, AuctionImage, Bid


class AuctionForm(ModelForm):
    class Meta:
        model = Auction
        fields = ["short_description", "description", "initial_price", "end_date"]


AuctionImageFormSet = inlineformset_factory(
    Auction,
    AuctionImage,
    fields=(
        "src",
        "description",
    ),
    min_num=0,
    extra=0,
    max_num=3,
    validate_min=True,
)  # type: ignore


class BidForm(ModelForm):
    class Meta:
        model = Bid
        fields = ["amount"]

apps/auctions/views.py
import json

import stripe
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, DetailView, TemplateView
from django.views.generic.list import ListView

from .forms import AuctionForm, AuctionImageFormSet, BidForm
from .models import Auction, Bid


class HomeView(TemplateView):
    template_name = "home.html"


class AuctionListView(ListView):
    context_object_name = "auctions"
    model = Auction
    paginate_by = 20
    template_name = "auctions/list.html"

    def get_queryset(self):
        queryset = super().get_queryset().filter(status=Auction.Status.NEW)

        if query := self.request.GET.get("q"):
            queryset = queryset.filter(
                Q(short_description__icontains=query) | Q(description__icontains=query)
            )

        return queryset


class AuctionDetailView(DetailView):
    model = Auction
    template_name = "auctions/detail.html"


class AuctionCreateView(LoginRequiredMixin, CreateView):
    form_class = AuctionForm
    template_name = "auctions/create.html"

    def get_context_data(self, **kwargs):
        if kwargs.get("image_formset") is None:
            kwargs["image_formset"] = AuctionImageFormSet(prefix="images")

        return super().get_context_data(**kwargs)

    def form_valid(self, form: AuctionForm) -> HttpResponse:
        auction = form.save(commit=False)
        auction.owner = self.request.user

        image_formset = AuctionImageFormSet(
            self.request.POST, self.request.FILES, instance=auction
        )

        if image_formset.is_valid():
            auction.save()
            image_formset.save()

            self.object = auction

            messages.success(self.request, _("Auction created successfully"))
        else:
            return self.form_invalid(form, image_formset)

        return super().form_valid(form)

    def form_invalid(self, form: AuctionForm, formset=None) -> HttpResponse:
        return self.render_to_response(
            self.get_context_data(form=form, image_formset=formset)
        )


class CreateBidView(LoginRequiredMixin, CreateView):
    form_class = BidForm
    template_name = "auctions/bid.html"

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        auction = get_object_or_404(Auction, pk=self.kwargs["pk"])

        if self.request.user == auction.owner:
            messages.error(request, _("You own the auction"))
            return HttpResponseRedirect(auction.get_absolute_url())

        if auction.current_bid and self.request.user == auction.current_bid.bidder:
            messages.error(request, _("Already bid on this auction"))
            return HttpResponseRedirect(auction.get_absolute_url())

        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("auctions:detail", kwargs={"pk": self.kwargs["pk"]})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        auction = get_object_or_404(Auction, pk=self.kwargs["pk"])

        kwargs["initial"] = {
            "amount": auction.current_price,
        }

        if self.request.method in ("POST", "PUT"):
            kwargs["instance"] = Bid(auction=auction, bidder=self.request.user)

        return kwargs


class PaymentView(LoginRequiredMixin, DetailView):
    model = Auction
    template_name = "auctions/pay.html"

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)

        if settings.STRIPE_LIVE_MODE:
            kwargs["public_key"] = settings.STRIPE_LIVE_PUBLIC_KEY
        else:
            kwargs["public_key"] = settings.STRIPE_TEST_PUBLIC_KEY

        kwargs["success_url"] = reverse("auctions:payment-successful")

        return kwargs

    def post(self, request: HttpRequest, pk: int) -> HttpResponse:
        auction = get_object_or_404(Auction, pk=pk)

        if settings.STRIPE_LIVE_MODE:
            stripe.api_key = settings.STRIPE_LIVE_SECRET_KEY
        else:
            stripe.api_key = settings.STRIPE_TEST_SECRET_KEY

        intent = stripe.PaymentIntent.create(
            amount=int(auction.current_price * 100),
            currency="usd",
            metadata={
                "auction_id": auction.id,
            },
        )

        data = {
            "secret": intent["client_secret"],
        }

        return JsonResponse(data)


class PaymentSuccessView(LoginRequiredMixin, TemplateView):
    template_name = "auctions/payment-successful.html"


@csrf_exempt
def payment_webhook(request: HttpRequest) -> HttpResponse:
    payload = request.body
    event = None

    if settings.STRIPE_LIVE_MODE:
        stripe.api_key = settings.STRIPE_LIVE_SECRET_KEY
    else:
        stripe.api_key = settings.STRIPE_TEST_SECRET_KEY

    try:
        event = stripe.Event.construct_from(json.loads(payload), stripe.api_key)
    except ValueError:
        return HttpResponse(status=400)

    if event.type == "charge.succeeded":
        # On a successfull card charge update the auction status to COMPLETE
        charge = event.data.object
        auction = Auction.objects.get(pk=int(charge["metadata"]["auction_id"]))
        auction.status = Auction.Status.COMPLETE
        auction.save()

    return HttpResponse(status=200)

templates/auctions/bid.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block content %}
  <main class="flex flex-col container mx-auto gap-8">
    <section class="flex flex-col gap-y-4 w-80 border-2 border-black p-4 rounded-md mx-auto">
      <h3 class="text-center">{% translate "Enter Bid" %}</h3>

      {% if form.non_field_errors %}
        <div class="notification notification--error">{{ form.non_field_errors }}</div>
      {% endif %}

      <form method="post" class="flex flex-col gap-y-4">
        {% csrf_token %}

        <div class="grid grid-cols-2 gap-y-4">
          {{ form.amount.label_tag }}

          <div class="flex flex-col">
            {{ form.amount }}
            {{ field }}

            {% for error in form.amount.errors %}<small class="font-bold text-red-500">{{ error }}</small>{% endfor %}
          </div>
        </div>

        <button class="button button__primary">{% translate "Submit" %}</button>
      </form>
    </section>
  </main>
{% endblock content %}

templates/auctions/create.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block content %}
  <main class="flex flex-col container mx-auto gap-8">
    <section class="flex flex-col gap-y-4 w-2/4 border-2 border-black p-4 rounded-md mx-auto">
      <h3 class="text-center">{% translate "Create Auction" %}</h3>

      <form method="post"
            class="flex flex-col gap-y-4"
            enctype="multipart/form-data"
            action="{% url 'auctions:create' %}">
        {% csrf_token %}

        {% if form.non_field_errors or image_formset.non_field_errors %}
          <div class="notification notification--error">
            {% if form.non_field_errors %}{{ form.non_field_errors }}{% endif %}
            {% if image_formset.non_field_errors %}{{ image_formset.non_field_errors }}{% endif %}
          </div>
        {% endif %}

        <div class="grid grid-cols-2 gap-4">
          {% for field in form %}
            {{ field.label_tag }}

            <div class="flex flex-col">
              {{ field }}

              {% for error in field.errors %}<small class="font-bold text-red-500">{{ error }}</small>{% endfor %}
            </div>
          {% endfor %}
        </div>

        <h5 class="text-center">
          {% translate "Images" %}

          <button type="button" class="button button__primary" onclick="addImageForm()">{% translate "Add Image" %}</button>
        </h5>

        {{ image_formset.management_form }}

        <div id="image-formset-container" class="grid grid-cols-3 gap-4">
          {% for form in image_formset %}
            <div class="flex flex-col gap-y-4">
              <div class="flex flex-col">
                {{ form.src }}

                {% for error in form.src.errors %}<small class="font-bold text-red-500">{{ error }}</small>{% endfor %}
              </div>

              {{ form.description.label_tag }}

              <div class="flex flex-col">
                {{ form.description }}

                {% for error in form.description.errors %}<small class="font-bold text-red-500">{{ error }}</small>{% endfor %}
              </div>
            </div>
          {% endfor %}
        </div>

        {% comment %}Empty formset to clone using js{% endcomment %}
        <div id="image-form-template" class="hidden">
          {% with formset=image_formset.empty_form %}
            <div class="flex flex-col gap-y-4">
              {{ formset.src }}

              {{ formset.description.label_tag }}

              {{ formset.description }}
            </div>
          {% endwith %}
        </div>

        <button class="button button__primary">{% translate "Submit" %}</button>
      </form>
    </section>
  </main>
{% endblock content %}

{% block scripts %}
  <script src="{% static 'js/auction-create.js' %}"></script>
{% endblock scripts %}

templates/auctions/detail.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block content %}
  <main class="flex flex-col container mx-auto gap-8">
    <div class="flex gap-x-8">
      <article class="flex gap-8 w-5/6">
        <section class="flex flex-col">
          {% with image=object.images.first %}
            <figure class="w-96 h-96">
              <img id="selected-image"
                   class="object-contain"
                   src="{{ image.src.url }}"
                   alt="{{ image.description }}">

              <figcaption id="selected-image-description" class="text-center">{{ image.description }}</figcaption>
            </figure>
          {% endwith %}

          <div class="flex gap-x-4 justify-center">
            {% for image in object.images.all %}
              <figure class="w-20 h-20">
                <img src="{{ image.src.url }}"
                     alt="{{ image.description }}"
                     class="image__preview"
                     data-description="{{ image.description }}"
                     onclick="setSelectedImage(event)">
              </figure>
            {% endfor %}
          </div>
        </section>

        <section class="flex flex-col gap-y-4">
          <h2>{{ object.short_description }}</h2>

          <p>{{ object.description }}</p>

          <strong>${{ object.current_price }}</strong>

          {% if user != object.owner and user != object.current_bid.bidder and not object.expired %}
            <p>
              <a class="button button__primary"
                 href="{% url 'auctions:bid' object.id %}">{% translate "Bid" %}</a>
            </p>
          {% endif %}
        </section>
      </article>

      <aside class="w-1/6">
        <h2>{% translate "Bids" %}</h2>

        {% now "Y-m-d H:i" as current_datetime %}

        {% for bid in object.bids.all %}
          <div>
            {% blocktranslate with amount=bid.amount bidder=bid.bidder %}
                <p>$ {{ amount }} - by {{ bidder }}</p>
                {% endblocktranslate %}
            <small>
              <em>
                {% if current_datetime == bid.date|date:"Y-m-d H:i" %}
                  {% translate "Just now" %}
                {% else %}
                  {% blocktranslate with bid_date_since=bid.date|timesince %}
                        {{ bid_date_since }} ago
                        {% endblocktranslate %}
                {% endif %}
              </em>
            </small>
          </div>
        {% empty %}
          <p>{% translate "There are no bids for this auction yet" %}</p>
        {% endfor %}
      </aside>
    </div>
  </main>
{% endblock content %}

{% block scripts %}
  <script src="{% static 'js/auction-detail.js' %}"></script>
{% endblock scripts %}

templates/auctions/list.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
  <main class="flex flex-col container mx-auto gap-8">
    <div class="grid grid-cols-4 gap-8">
      {% for auction in auctions %}
        <a href="{% url 'auctions:detail' pk=auction.id %}">
          {% include "auctions/elements/card.html" with auction=auction %}
        </a>
      {% endfor %}
    </div>

    <nav class="flex justify-center" role="navigation" aria-label="pagination">
      <ul class="flex gap-x-4">
        {% if page_obj.has_previous %}
          <li>
            <a class="button" href="?page={{ page_obj.previous_page_number }}">{% translate "Previous" %}</a>
          </li>
        {% endif %}

        {% for page_num in page_obj.paginator.page_range %}
          <li>
            <a class="button{% if page_num == page_obj.number %} button__primary{% endif %}"
               href="?page={{ page_num }}"
               aria-label="Goto page {{ page_num }}">{{ page_num }}</a>
          </li>
        {% endfor %}

        {% if page_obj.has_next %}
          <li>
            <a class="button" href="?page={{ page_obj.next_page_number }}">{% translate "Next page" %}</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </main>
{% endblock content %}

templates/auctions/pay.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block content %}
  <main class="flex flex-col container mx-auto gap-8">
    <div class="grid w-1/2 mx-auto grid-cols-2 gap-8">
      {% include "auctions/elements/card.html" with auction=auction %}

      <form id="payment-form" class="flex flex-col gap-y-4">
        <div id="card-element" class="border-2 border-black rounded-md px-2 py-1"></div>

        <button class="button button__primary">{% translate "Pay" %}</button>
      </form>
    </div>
  </main>
{% endblock content %}

{% block scripts %}
  {{ public_key|json_script:'stripe-key' }}
  {{ success_url|json_script:'success-url' }}
  <script src="https://js.stripe.com/v3/"></script>
  <script src="{% static 'js/js-cookie-2.2.1.min.js' %}"></script>
  <script src="{% static 'js/payments.js' %}"></script>
{% endblock scripts %}

templates/auctions/payment-successful.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
  <main class="flex flex-col container mx-auto gap-8">
    <section class="text-center flex flex-col gap-y-4 w-80 border-2 border-black p-4 rounded-md mx-auto">
      <h3>{% translate "Thank you!" %}</h3>
      <p>{% translate "Your payment was sent. You will receive a notification once it is validated." %}</p>
    </section>
  </main>
{% endblock content %}