apps/accounts/urls.py
from django.urls import path

from .views import AccountProfileView

app_name = "accounts"

urlpatterns = [
    path("profile", AccountProfileView.as_view(), name="profile"),
]

apps/auctions/urls.py
from django.urls import path

from .views import (
    AuctionCreateView,
    AuctionDetailView,
    AuctionListView,
    CreateBidView,
    PaymentSuccessView,
    PaymentView,
    payment_webhook,
)

app_name = "auctions"

urlpatterns = [
    path("", AuctionListView.as_view(), name="list"),
    path("<int:pk>", AuctionDetailView.as_view(), name="detail"),
    path("<int:pk>/bid", CreateBidView.as_view(), name="bid"),
    path("create", AuctionCreateView.as_view(), name="create"),
    path("<int:pk>/pay", PaymentView.as_view(), name="pay"),
    path("payment/success", PaymentSuccessView.as_view(), name="payment-successful"),
    path("payment/hook", payment_webhook, name="payment-hook"),
]

config/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from apps.auctions import views as auctions_views

urlpatterns = [
    path("", auctions_views.HomeView.as_view(), name="home"),
    path("accounts/", include("apps.accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("auctions/", include("apps.auctions.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    if apps.is_installed("debug_toolbar"):
        urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>
      {% block title %}
        Auctioneer
      {% endblock title %}
    </title>

    <link href="{% static 'css/main.css' %}" rel="stylesheet">
  </head>

  <body>
    <header class="container mx-auto p-4">
      <nav class="flex justify-between gap-x-4">
        <ul class="flex items-center gap-x-4">
          <li>
            <a href="{% url 'home' %}">Auctioneer</a>
          </li>
          <li>
            <a href="{% url 'auctions:list' %}">{% translate "Buy" %}</a>
          </li>
          <li>
            <a href="{% url 'auctions:create' %}">{% translate "Sell" %}</a>
          </li>
          <li>
            <form method="get" role="search" action="{% url 'auctions:list' %}">
              <input type="text" name="q" placeholder="{% translate "Search auctions" %}">
              <button type="submit" class="button button__primary">Search</button>
            </form>
          </li>
        </ul>

        <ul class="flex items-center gap-x-4">
          {% if user.is_authenticated %}
            <li>
              <a href="{% url 'accounts:profile' %}">{% translate "Profile" %}</a>
            </li>
            <li>
              <a href="{% url 'account_logout' %}">{% translate "Logout" %}</a>
            </li>
          {% else %}
            <li>
              <a href="{% url 'account_login' %}">{% translate "Log in" %}</a>
            </li>
            <li>
              <a href="{% url 'account_signup' %}">{% translate "Sign up" %}</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </header>

    {% if messages %}
      <section class="flex gap-y-4 justify-center container mx-auto">
        {% for message in messages %}
          <div class="notification notification--{{ message.tags }}">{{ message }}</div>
        {% endfor %}
      </section>
    {% endif %}

    {% block content %}
      {# Override page specific content using this block #}
    {% endblock content %}

    <footer class="container mx-auto mt-auto p-4 text-center">
      <p>Auctioneer - {% now "Y" %}</p>
    </footer>

    {% block scripts %}
      {# Override page specific scripts using this block #}
    {% endblock scripts %}
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block content %}
  <main class="flex flex-col container mx-auto gap-8">
    <h1 class="text-center">Welcome to auctioneer!</h1>

    <p>{% lorem %}</p>

    <hr>

    <article class="flex flex-col gap-y-8">
      <header class="text-center">
        <h2>Bidder steps</h2>
      </header>

      <article class="flex flex-row gap-x-4">
        <figure>
          <img src="{% static 'img/sq_image_ph.webp' %}"
               alt="{% translate "An image describing step one of the bidding process" %}" />
        </figure>

        <section>
          <h3>Bid step 1</h3>

          <p>{% lorem %}</p>
        </section>
      </article>

      <article class="flex flex-row gap-x-4">
        <section>
          <h3>Bid step 2</h3>

          <p>{% lorem %}</p>
        </section>

        <figure>
          <img src="{% static 'img/sq_image_ph.webp' %}"
               alt="{% translate "An image describing step two of the bidding process" %}" />
        </figure>
      </article>

      <article class="flex flex-row gap-x-4">
        <figure>
          <img src="{% static 'img/sq_image_ph.webp' %}"
               alt="{% translate "An image describing step three of the bidding process" %}" />
        </figure>

        <section>
          <h3>Bid step 3</h3>

          <p>{% lorem %}</p>
        </section>
      </article>

      <article class="flex flex-row gap-x-4">
        <section>
          <h3>Bid step 4</h3>

          <p>{% lorem %}</p>
        </section>

        <figure>
          <img src="{% static 'img/sq_image_ph.webp' %}"
               alt="{% translate "An image describing step four of the bidding process" %}" />
        </figure>
      </article>

      <footer class="flex justify-center">
        <a href="{% url 'auctions:list' %}" class="button button__primary">Start bidding now!</a>
      </footer>
    </article>

    <hr>

    <article class="flex flex-col gap-y-8">
      <header class="text-center">
        <h2>Seller steps</h2>
      </header>

      <section class="flex flex-row gap-x-4">
        <figure>
          <img src="{% static 'img/sq_image_ph.webp' %}"
               alt="{% translate "An image describing step one of the seller process" %}" />
        </figure>

        <section>
          <h3>Seller step 1</h3>

          <p>{% lorem %}</p>
        </section>
      </section>

      <section class="flex flex-row gap-x-4">
        <section>
          <h3>Seller step 2</h3>

          <p>{% lorem %}</p>
        </section>

        <figure>
          <img src="{% static 'img/sq_image_ph.webp' %}"
               alt="{% translate "An image describing step two of the seller process" %}" />
        </figure>
      </section>

      <section class="flex flex-row gap-x-4">
        <figure>
          <img src="{% static 'img/sq_image_ph.webp' %}"
               alt="{% translate "An image describing step three of the seller process" %}" />
        </figure>

        <section>
          <h3>Seller step 3</h3>

          <p>{% lorem %}</p>
        </section>
      </section>

      <footer class="flex justify-center">
        <a href="{% url 'auctions:create' %}" class="button button__primary">Start selling now!</a>
      </footer>
    </article>
  </main>
{% endblock content %}